// <auto-generated />
using System;
using CompalintsSystem.EF.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CompalintsSystem.EF.Migrations
{
    [DbContext(typeof(AppCompalintsContextDB))]
    [Migration("20240126141017_abda")]
    partial class abda
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Identity")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CompalintsSystem.Core.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("CollegesId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentsId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SocietyId")
                        .HasColumnType("int");

                    b.Property<int>("SubDepartmentsId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserRoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("originatorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CollegesId");

                    b.HasIndex("DepartmentsId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("SocietyId");

                    b.HasIndex("SubDepartmentsId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.Colleges", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Collegess");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "كلية الطب العلوم الصحية "
                        },
                        new
                        {
                            Id = 2,
                            Name = " كلية الهندسة وتقنية المعلومات"
                        },
                        new
                        {
                            Id = 3,
                            Name = " كلية التجارة والاقتصاد"
                        },
                        new
                        {
                            Id = 4,
                            Name = "كلية العلوم التطبيقية والانسانية "
                        },
                        new
                        {
                            Id = 5,
                            Name = "كلية الاعمال باللغة الانجليزية"
                        });
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.Compalints_Solution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContentSolution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateSolution")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAccept")
                        .HasColumnType("bit");

                    b.Property<string>("ReasonWhySolutionRejected")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolutionProvIdentity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolutionProvName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UploadsComplainteId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UploadsComplainteId");

                    b.HasIndex("UserId");

                    b.ToTable("Compalints_Solutions");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.ComplaintsRejected", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateSolution")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectedProvName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectedUserProvIdentity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UploadsComplainteId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("reume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UploadsComplainteId");

                    b.HasIndex("UserId");

                    b.ToTable("ComplaintsRejecteds");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.ComplatinClassfaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ComplatinClassfactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "عالية"
                        },
                        new
                        {
                            Id = 2,
                            Name = "متوسطة"
                        },
                        new
                        {
                            Id = 3,
                            Name = "منخفضة"
                        });
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.Departments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CollegesId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CollegesId");

                    b.ToTable("Departmentss");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CollegesId = 1,
                            Name = "طب بشري"
                        },
                        new
                        {
                            Id = 2,
                            CollegesId = 1,
                            Name = "صيدلة"
                        },
                        new
                        {
                            Id = 3,
                            CollegesId = 1,
                            Name = "مختبرات"
                        },
                        new
                        {
                            Id = 4,
                            CollegesId = 1,
                            Name = "تمريض"
                        },
                        new
                        {
                            Id = 5,
                            CollegesId = 2,
                            Name = "هندسة مدني "
                        },
                        new
                        {
                            Id = 6,
                            CollegesId = 2,
                            Name = "هندسة معماري"
                        },
                        new
                        {
                            Id = 7,
                            CollegesId = 2,
                            Name = "علوم حاسوب"
                        },
                        new
                        {
                            Id = 8,
                            CollegesId = 2,
                            Name = " نظم معلومات حاسوبية"
                        },
                        new
                        {
                            Id = 9,
                            CollegesId = 2,
                            Name = "الامن السيبراني والشبكات"
                        },
                        new
                        {
                            Id = 10,
                            CollegesId = 3,
                            Name = "محاسبة"
                        },
                        new
                        {
                            Id = 11,
                            CollegesId = 3,
                            Name = "ادارة اعمال "
                        },
                        new
                        {
                            Id = 12,
                            CollegesId = 3,
                            Name = "علوم مالية ومصرفية"
                        },
                        new
                        {
                            Id = 13,
                            CollegesId = 3,
                            Name = "ادارة اعمال دولية"
                        },
                        new
                        {
                            Id = 14,
                            CollegesId = 4,
                            Name = "الشرعة والقانون"
                        },
                        new
                        {
                            Id = 15,
                            CollegesId = 4,
                            Name = "علوم زراعية"
                        },
                        new
                        {
                            Id = 16,
                            CollegesId = 4,
                            Name = "قران كريم وعلومة _علوم الحياة"
                        },
                        new
                        {
                            Id = 17,
                            CollegesId = 4,
                            Name = "لغة انجليزي"
                        },
                        new
                        {
                            Id = 25,
                            CollegesId = 4,
                            Name = "دراسات عربية"
                        },
                        new
                        {
                            Id = 18,
                            CollegesId = 4,
                            Name = "كيمياء"
                        },
                        new
                        {
                            Id = 19,
                            CollegesId = 4,
                            Name = "فيزياء"
                        },
                        new
                        {
                            Id = 20,
                            CollegesId = 4,
                            Name = "رياضيات"
                        },
                        new
                        {
                            Id = 21,
                            CollegesId = 4,
                            Name = "جغرافيا_تاريخ"
                        },
                        new
                        {
                            Id = 22,
                            CollegesId = 4,
                            Name = "ترجمة"
                        },
                        new
                        {
                            Id = 23,
                            CollegesId = 5,
                            Name = "محاسبة وتمويل"
                        },
                        new
                        {
                            Id = 24,
                            CollegesId = 5,
                            Name = "ادارة اعمال دولية"
                        });
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.Proposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BeneficiarieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateSubmeted")
                        .HasColumnType("datetime2")
                        .HasComment("تحديد وقت ادخال الصف في قاعدية البيانات");

                    b.Property<string>("DescProposal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitileProposal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Proposals");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.Society", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Societys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "الملتقى"
                        },
                        new
                        {
                            Id = 2,
                            Name = " موظف الشكوى"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ادارة عامة"
                        });
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.StagesComplaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StagesComplaints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "موظف الشكوى"
                        },
                        new
                        {
                            Id = 2,
                            Name = "رئيس القسم"
                        },
                        new
                        {
                            Id = 3,
                            Name = "عميد الكلية"
                        },
                        new
                        {
                            Id = 4,
                            Name = " الادارة العامة"
                        });
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.StatusCompalint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StatusCompalints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "جديدة"
                        },
                        new
                        {
                            Id = 2,
                            Name = "محلولة"
                        },
                        new
                        {
                            Id = 3,
                            Name = "مرفوضة"
                        },
                        new
                        {
                            Id = 4,
                            Name = "مغلقة"
                        },
                        new
                        {
                            Id = 5,
                            Name = "مرفوعة"
                        });
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.SubDepartments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentsId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentsId");

                    b.ToTable("SubDepartmentss");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentsId = 1,
                            Name = " الاول"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentsId = 1,
                            Name = " الثاني"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentsId = 1,
                            Name = " الثالث"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentsId = 1,
                            Name = " الرابع"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentsId = 1,
                            Name = " الخامس"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentsId = 1,
                            Name = " السادس"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentsId = 1,
                            Name = " السابع"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentsId = 2,
                            Name = " الاول"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentsId = 2,
                            Name = " الثاني"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentsId = 2,
                            Name = " الثالث"
                        },
                        new
                        {
                            Id = 11,
                            DepartmentsId = 2,
                            Name = " الرابع"
                        },
                        new
                        {
                            Id = 12,
                            DepartmentsId = 2,
                            Name = " الخامس"
                        },
                        new
                        {
                            Id = 13,
                            DepartmentsId = 3,
                            Name = " الاول"
                        },
                        new
                        {
                            Id = 14,
                            DepartmentsId = 3,
                            Name = " الثاني"
                        },
                        new
                        {
                            Id = 15,
                            DepartmentsId = 3,
                            Name = " الثالث"
                        },
                        new
                        {
                            Id = 16,
                            DepartmentsId = 3,
                            Name = " الرابع"
                        },
                        new
                        {
                            Id = 17,
                            DepartmentsId = 4,
                            Name = " الاول"
                        },
                        new
                        {
                            Id = 18,
                            DepartmentsId = 4,
                            Name = " الثاني"
                        },
                        new
                        {
                            Id = 19,
                            DepartmentsId = 4,
                            Name = " الثالث"
                        },
                        new
                        {
                            Id = 20,
                            DepartmentsId = 4,
                            Name = " الرابع"
                        },
                        new
                        {
                            Id = 21,
                            DepartmentsId = 5,
                            Name = " الاول"
                        },
                        new
                        {
                            Id = 22,
                            DepartmentsId = 5,
                            Name = " الثاني"
                        },
                        new
                        {
                            Id = 23,
                            DepartmentsId = 5,
                            Name = " الثالث"
                        },
                        new
                        {
                            Id = 24,
                            DepartmentsId = 5,
                            Name = " الرابع"
                        },
                        new
                        {
                            Id = 25,
                            DepartmentsId = 6,
                            Name = " الاول"
                        },
                        new
                        {
                            Id = 26,
                            DepartmentsId = 6,
                            Name = " الثاني"
                        },
                        new
                        {
                            Id = 27,
                            DepartmentsId = 6,
                            Name = " الثالث"
                        },
                        new
                        {
                            Id = 28,
                            DepartmentsId = 6,
                            Name = " الرابع"
                        },
                        new
                        {
                            Id = 29,
                            DepartmentsId = 7,
                            Name = " الاول"
                        },
                        new
                        {
                            Id = 30,
                            DepartmentsId = 7,
                            Name = " الثاني"
                        },
                        new
                        {
                            Id = 31,
                            DepartmentsId = 7,
                            Name = " الثالث"
                        },
                        new
                        {
                            Id = 32,
                            DepartmentsId = 7,
                            Name = " الرابع"
                        },
                        new
                        {
                            Id = 33,
                            DepartmentsId = 8,
                            Name = " الاول"
                        },
                        new
                        {
                            Id = 34,
                            DepartmentsId = 8,
                            Name = " الثاني"
                        },
                        new
                        {
                            Id = 35,
                            DepartmentsId = 8,
                            Name = " الثالث"
                        },
                        new
                        {
                            Id = 36,
                            DepartmentsId = 8,
                            Name = " الرابع"
                        },
                        new
                        {
                            Id = 37,
                            DepartmentsId = 9,
                            Name = " الاول"
                        },
                        new
                        {
                            Id = 38,
                            DepartmentsId = 9,
                            Name = " الثاني"
                        },
                        new
                        {
                            Id = 39,
                            DepartmentsId = 9,
                            Name = " الثالث"
                        },
                        new
                        {
                            Id = 40,
                            DepartmentsId = 9,
                            Name = " الرابع"
                        },
                        new
                        {
                            Id = 41,
                            DepartmentsId = 10,
                            Name = " الاول"
                        },
                        new
                        {
                            Id = 42,
                            DepartmentsId = 10,
                            Name = " الثاني"
                        },
                        new
                        {
                            Id = 43,
                            DepartmentsId = 10,
                            Name = " الثالث"
                        },
                        new
                        {
                            Id = 44,
                            DepartmentsId = 10,
                            Name = " الرابع"
                        },
                        new
                        {
                            Id = 45,
                            DepartmentsId = 11,
                            Name = " الاول"
                        },
                        new
                        {
                            Id = 46,
                            DepartmentsId = 11,
                            Name = " الثاني"
                        },
                        new
                        {
                            Id = 47,
                            DepartmentsId = 11,
                            Name = " الثالث"
                        },
                        new
                        {
                            Id = 48,
                            DepartmentsId = 11,
                            Name = " الرابع"
                        },
                        new
                        {
                            Id = 49,
                            DepartmentsId = 12,
                            Name = " الاول"
                        },
                        new
                        {
                            Id = 50,
                            DepartmentsId = 12,
                            Name = " الثاني"
                        },
                        new
                        {
                            Id = 51,
                            DepartmentsId = 12,
                            Name = " الثالث"
                        },
                        new
                        {
                            Id = 52,
                            DepartmentsId = 12,
                            Name = " الرابع"
                        },
                        new
                        {
                            Id = 53,
                            DepartmentsId = 13,
                            Name = " الاول"
                        },
                        new
                        {
                            Id = 54,
                            DepartmentsId = 13,
                            Name = " الثاني"
                        },
                        new
                        {
                            Id = 55,
                            DepartmentsId = 13,
                            Name = " الثالث"
                        },
                        new
                        {
                            Id = 56,
                            DepartmentsId = 13,
                            Name = " الرابع"
                        },
                        new
                        {
                            Id = 57,
                            DepartmentsId = 14,
                            Name = " الاول"
                        },
                        new
                        {
                            Id = 58,
                            DepartmentsId = 14,
                            Name = " الثاني"
                        },
                        new
                        {
                            Id = 59,
                            DepartmentsId = 14,
                            Name = " الثالث"
                        },
                        new
                        {
                            Id = 60,
                            DepartmentsId = 14,
                            Name = " الرابع"
                        },
                        new
                        {
                            Id = 61,
                            DepartmentsId = 15,
                            Name = " الاول"
                        },
                        new
                        {
                            Id = 62,
                            DepartmentsId = 15,
                            Name = " الثاني"
                        },
                        new
                        {
                            Id = 63,
                            DepartmentsId = 15,
                            Name = " الثالث"
                        },
                        new
                        {
                            Id = 64,
                            DepartmentsId = 15,
                            Name = " الرابع"
                        },
                        new
                        {
                            Id = 65,
                            DepartmentsId = 16,
                            Name = " الاول"
                        },
                        new
                        {
                            Id = 66,
                            DepartmentsId = 16,
                            Name = " الثاني"
                        },
                        new
                        {
                            Id = 67,
                            DepartmentsId = 16,
                            Name = " الثالث"
                        },
                        new
                        {
                            Id = 68,
                            DepartmentsId = 16,
                            Name = " الرابع"
                        },
                        new
                        {
                            Id = 69,
                            DepartmentsId = 17,
                            Name = " الاول"
                        },
                        new
                        {
                            Id = 70,
                            DepartmentsId = 17,
                            Name = " الثاني"
                        },
                        new
                        {
                            Id = 71,
                            DepartmentsId = 17,
                            Name = " الثالث"
                        },
                        new
                        {
                            Id = 72,
                            DepartmentsId = 17,
                            Name = " الرابع"
                        },
                        new
                        {
                            Id = 73,
                            DepartmentsId = 18,
                            Name = " الاول"
                        },
                        new
                        {
                            Id = 74,
                            DepartmentsId = 18,
                            Name = " الثاني"
                        },
                        new
                        {
                            Id = 75,
                            DepartmentsId = 18,
                            Name = " الثالث"
                        },
                        new
                        {
                            Id = 76,
                            DepartmentsId = 18,
                            Name = " الرابع"
                        },
                        new
                        {
                            Id = 77,
                            DepartmentsId = 19,
                            Name = " الاول"
                        },
                        new
                        {
                            Id = 78,
                            DepartmentsId = 19,
                            Name = " الثاني"
                        },
                        new
                        {
                            Id = 79,
                            DepartmentsId = 19,
                            Name = " الثالث"
                        },
                        new
                        {
                            Id = 80,
                            DepartmentsId = 19,
                            Name = " الرابع"
                        },
                        new
                        {
                            Id = 81,
                            DepartmentsId = 20,
                            Name = " الاول"
                        },
                        new
                        {
                            Id = 82,
                            DepartmentsId = 20,
                            Name = " الثاني"
                        },
                        new
                        {
                            Id = 83,
                            DepartmentsId = 20,
                            Name = " الثالث"
                        },
                        new
                        {
                            Id = 84,
                            DepartmentsId = 20,
                            Name = " الرابع"
                        },
                        new
                        {
                            Id = 85,
                            DepartmentsId = 21,
                            Name = " الاول"
                        },
                        new
                        {
                            Id = 86,
                            DepartmentsId = 21,
                            Name = " الثاني"
                        },
                        new
                        {
                            Id = 87,
                            DepartmentsId = 21,
                            Name = " الثالث"
                        },
                        new
                        {
                            Id = 88,
                            DepartmentsId = 21,
                            Name = " الرابع"
                        },
                        new
                        {
                            Id = 89,
                            DepartmentsId = 22,
                            Name = " الاول"
                        },
                        new
                        {
                            Id = 90,
                            DepartmentsId = 22,
                            Name = " الثاني"
                        },
                        new
                        {
                            Id = 91,
                            DepartmentsId = 22,
                            Name = " الثالث"
                        },
                        new
                        {
                            Id = 92,
                            DepartmentsId = 22,
                            Name = " الرابع"
                        },
                        new
                        {
                            Id = 93,
                            DepartmentsId = 23,
                            Name = " الاول"
                        },
                        new
                        {
                            Id = 94,
                            DepartmentsId = 23,
                            Name = " الثاني"
                        },
                        new
                        {
                            Id = 95,
                            DepartmentsId = 23,
                            Name = " الثالث"
                        },
                        new
                        {
                            Id = 96,
                            DepartmentsId = 23,
                            Name = " الرابع"
                        },
                        new
                        {
                            Id = 97,
                            DepartmentsId = 24,
                            Name = " الاول"
                        },
                        new
                        {
                            Id = 98,
                            DepartmentsId = 24,
                            Name = " الثاني"
                        },
                        new
                        {
                            Id = 99,
                            DepartmentsId = 24,
                            Name = " الثالث"
                        },
                        new
                        {
                            Id = 100,
                            DepartmentsId = 24,
                            Name = " الرابع"
                        },
                        new
                        {
                            Id = 101,
                            DepartmentsId = 25,
                            Name = " الاول"
                        },
                        new
                        {
                            Id = 102,
                            DepartmentsId = 25,
                            Name = " الثاني"
                        },
                        new
                        {
                            Id = 103,
                            DepartmentsId = 25,
                            Name = " الثالث"
                        },
                        new
                        {
                            Id = 104,
                            DepartmentsId = 25,
                            Name = " الرابع"
                        },
                        new
                        {
                            Id = 105,
                            DepartmentsId = 5,
                            Name = " الخامس"
                        },
                        new
                        {
                            Id = 106,
                            DepartmentsId = 6,
                            Name = " الخامس"
                        });
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.TypeCommunication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsersNameAddType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeCommunications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 26, 17, 10, 15, 929, DateTimeKind.Local).AddTicks(1008),
                            Type = "بلاغ أكاديمي",
                            UsersNameAddType = "قيمة افتراضية من النضام"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 26, 17, 10, 15, 929, DateTimeKind.Local).AddTicks(1023),
                            Type = "بلاغ إداري",
                            UsersNameAddType = "قيمة افتراضية من النضام"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 1, 26, 17, 10, 15, 929, DateTimeKind.Local).AddTicks(1029),
                            Type = "بلاغ تأديبي",
                            UsersNameAddType = "قيمة افتراضية من النضام"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 1, 26, 17, 10, 15, 929, DateTimeKind.Local).AddTicks(1034),
                            Type = "بلاغ تمييز",
                            UsersNameAddType = "قيمة افتراضية من النضام"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 1, 26, 17, 10, 15, 929, DateTimeKind.Local).AddTicks(1039),
                            Type = "بلاغ أمان وصحة",
                            UsersNameAddType = "قيمة افتراضية من النضام"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 1, 26, 17, 10, 15, 929, DateTimeKind.Local).AddTicks(1043),
                            Type = "بلاغ تحرش",
                            UsersNameAddType = "قيمة افتراضية من النضام"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 1, 26, 17, 10, 15, 929, DateTimeKind.Local).AddTicks(1048),
                            Type = "تلاعب بالحلول",
                            UsersNameAddType = "قيمة افتراضية من النضام"
                        });
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.TypeComplaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsersNameAddType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeComplaints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 26, 17, 10, 15, 930, DateTimeKind.Local).AddTicks(280),
                            Type = "شكاوى أكاديمية",
                            UsersNameAddType = "قيمة افتراضية من النضام"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 26, 17, 10, 15, 930, DateTimeKind.Local).AddTicks(1043),
                            Type = "شكاوى إدارية",
                            UsersNameAddType = "قيمة افتراضية من النضام"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 1, 26, 17, 10, 15, 930, DateTimeKind.Local).AddTicks(1049),
                            Type = "شكاوى تقنية",
                            UsersNameAddType = "قيمة افتراضية من النضام"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 1, 26, 17, 10, 15, 930, DateTimeKind.Local).AddTicks(1054),
                            Type = "شكاوى تمييز وتحيز",
                            UsersNameAddType = "قيمة افتراضية من النضام"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 1, 26, 17, 10, 15, 930, DateTimeKind.Local).AddTicks(1060),
                            Type = "شكاوى سلوك غير لائق",
                            UsersNameAddType = "قيمة افتراضية من النضام"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 1, 26, 17, 10, 15, 930, DateTimeKind.Local).AddTicks(1065),
                            Type = "شكاوى الأمان والسلامة",
                            UsersNameAddType = "قيمة افتراضية من النضام"
                        });
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.UpComplaintCause", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateUp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpProvName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpUserProvIdentity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UploadsComplainteId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UploadsComplainteId");

                    b.HasIndex("UserId");

                    b.ToTable("UpComplaintCauses");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.UploadsComplainte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CollegesId")
                        .HasColumnType("int");

                    b.Property<int?>("ComplatinClassfactionId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentsId")
                        .HasColumnType("int");

                    b.Property<string>("DescComplaint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropBeneficiarie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReturnedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Size")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("SocietyId")
                        .HasColumnType("int");

                    b.Property<int>("StagesComplaintId")
                        .HasColumnType("int");

                    b.Property<int>("StatusCompalintId")
                        .HasColumnType("int");

                    b.Property<int>("SubDepartmentsId")
                        .HasColumnType("int");

                    b.Property<string>("TitleComplaint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Today")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeComplaintId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CollegesId");

                    b.HasIndex("ComplatinClassfactionId");

                    b.HasIndex("DepartmentsId");

                    b.HasIndex("SocietyId");

                    b.HasIndex("StagesComplaintId");

                    b.HasIndex("StatusCompalintId");

                    b.HasIndex("SubDepartmentsId");

                    b.HasIndex("TypeComplaintId");

                    b.ToTable("UploadsComplaintes");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.UsersCommunication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BenfPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CollegesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentsId")
                        .HasColumnType("int");

                    b.Property<int>("SubDepartmentsId")
                        .HasColumnType("int");

                    b.Property<string>("Titile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeCommuncationId")
                        .HasColumnType("int");

                    b.Property<string>("reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reportSubmitterId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("reportSubmitterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reporteeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CollegesId");

                    b.HasIndex("DepartmentsId");

                    b.HasIndex("SubDepartmentsId");

                    b.HasIndex("TypeCommuncationId");

                    b.HasIndex("reportSubmitterId");

                    b.ToTable("UsersCommunications");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "2e803883-c018-4f7c-90e3-c3c1db0d8f00",
                            ConcurrencyStamp = "ecae0872-d9db-4ead-96bb-a691de047b0e",
                            Name = "AdminGeneralFederation",
                            NormalizedName = "ADMINGENERALFEDERATION"
                        },
                        new
                        {
                            Id = "7f95d3fd-8840-466e-9da6-d7dcf06298de",
                            ConcurrencyStamp = "103efdba-ff1b-4bb9-8b4d-8f6a26946f02",
                            Name = "AdminColleges",
                            NormalizedName = "ADMINCOLLEGES"
                        },
                        new
                        {
                            Id = "81b7a93d-4221-4d50-884c-08d98676a9c8",
                            ConcurrencyStamp = "973b7325-e112-4d48-81f5-80f19cee9792",
                            Name = "AdminDepartments",
                            NormalizedName = "ADMINDEPARTMENTS"
                        },
                        new
                        {
                            Id = "64a8ff4a-f4a2-405c-9c1a-85f0f9f46145",
                            ConcurrencyStamp = "27fd1341-dba0-450a-ae71-7e602c28d9b6",
                            Name = "AdminSubDepartments",
                            NormalizedName = "ADMINSUBDEPARTMENTS"
                        },
                        new
                        {
                            Id = "8faa31eb-ded0-4711-8e0b-0f509c4b332f",
                            ConcurrencyStamp = "93efadaa-2a40-4a8a-a737-64ef3168a10e",
                            Name = "Beneficiarie",
                            NormalizedName = "BENEFICIARIE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.ApplicationUser", b =>
                {
                    b.HasOne("CompalintsSystem.Core.Models.Colleges", "Colleges")
                        .WithMany("Users")
                        .HasForeignKey("CollegesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.Departments", "Departments")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.Society", "Societies")
                        .WithMany("Users")
                        .HasForeignKey("SocietyId");

                    b.HasOne("CompalintsSystem.Core.Models.SubDepartments", "SubDepartments")
                        .WithMany("Users")
                        .HasForeignKey("SubDepartmentsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Colleges");

                    b.Navigation("Departments");

                    b.Navigation("Societies");

                    b.Navigation("SubDepartments");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.Compalints_Solution", b =>
                {
                    b.HasOne("CompalintsSystem.Core.Models.UploadsComplainte", "CompalintsHasSolution")
                        .WithMany("Compalints_Solutions")
                        .HasForeignKey("UploadsComplainteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.ApplicationUser", "UserAddSolution")
                        .WithMany("Compalints_Solutions")
                        .HasForeignKey("UserId");

                    b.Navigation("CompalintsHasSolution");

                    b.Navigation("UserAddSolution");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.ComplaintsRejected", b =>
                {
                    b.HasOne("CompalintsSystem.Core.Models.UploadsComplainte", "CompalintsRejected")
                        .WithMany("ComplaintsRejecteds")
                        .HasForeignKey("UploadsComplainteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.ApplicationUser", "UserRejectComplaint")
                        .WithMany("ComplaintsRejecteds")
                        .HasForeignKey("UserId");

                    b.Navigation("CompalintsRejected");

                    b.Navigation("UserRejectComplaint");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.Departments", b =>
                {
                    b.HasOne("CompalintsSystem.Core.Models.Colleges", "Colleges")
                        .WithMany("Departmentss")
                        .HasForeignKey("CollegesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colleges");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.SubDepartments", b =>
                {
                    b.HasOne("CompalintsSystem.Core.Models.Departments", "Departments")
                        .WithMany("SubDepartmentss")
                        .HasForeignKey("DepartmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.UpComplaintCause", b =>
                {
                    b.HasOne("CompalintsSystem.Core.Models.UploadsComplainte", "CompalintUp")
                        .WithMany("ComplaintsUp")
                        .HasForeignKey("UploadsComplainteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.ApplicationUser", "UserUpComplaint")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("CompalintUp");

                    b.Navigation("UserUpComplaint");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.UploadsComplainte", b =>
                {
                    b.HasOne("CompalintsSystem.Core.Models.ApplicationUser", null)
                        .WithMany("UploadsComplaintes")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("CompalintsSystem.Core.Models.Colleges", "Colleges")
                        .WithMany("UploadsComplaintes")
                        .HasForeignKey("CollegesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.ComplatinClassfaction", "ComplatinClassfaction")
                        .WithMany("UploadsComplainte")
                        .HasForeignKey("ComplatinClassfactionId");

                    b.HasOne("CompalintsSystem.Core.Models.Departments", "Departments")
                        .WithMany("UploadsComplaintes")
                        .HasForeignKey("DepartmentsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.Society", "Society")
                        .WithMany()
                        .HasForeignKey("SocietyId");

                    b.HasOne("CompalintsSystem.Core.Models.StagesComplaint", "StagesComplaint")
                        .WithMany("UploadsComplainte")
                        .HasForeignKey("StagesComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.StatusCompalint", "StatusCompalint")
                        .WithMany("UploadsComplainte")
                        .HasForeignKey("StatusCompalintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.SubDepartments", "SubDepartments")
                        .WithMany("UploadsComplaintes")
                        .HasForeignKey("SubDepartmentsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.TypeComplaint", "TypeComplaint")
                        .WithMany("UploadsComplaintes")
                        .HasForeignKey("TypeComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colleges");

                    b.Navigation("ComplatinClassfaction");

                    b.Navigation("Departments");

                    b.Navigation("Society");

                    b.Navigation("StagesComplaint");

                    b.Navigation("StatusCompalint");

                    b.Navigation("SubDepartments");

                    b.Navigation("TypeComplaint");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.UsersCommunication", b =>
                {
                    b.HasOne("CompalintsSystem.Core.Models.Colleges", "Colleges")
                        .WithMany("UsersCommunications")
                        .HasForeignKey("CollegesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.Departments", "Departments")
                        .WithMany("UsersCommunications")
                        .HasForeignKey("DepartmentsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.SubDepartments", "SubDepartments")
                        .WithMany("UsersCommunications")
                        .HasForeignKey("SubDepartmentsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.TypeCommunication", "TypeCommunication")
                        .WithMany("UsersCommunications")
                        .HasForeignKey("TypeCommuncationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.ApplicationUser", "reportSubmitter")
                        .WithMany("UsersCommunications")
                        .HasForeignKey("reportSubmitterId");

                    b.Navigation("Colleges");

                    b.Navigation("Departments");

                    b.Navigation("reportSubmitter");

                    b.Navigation("SubDepartments");

                    b.Navigation("TypeCommunication");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.HasOne("CompalintsSystem.Core.Models.ApplicationUser", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CompalintsSystem.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CompalintsSystem.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CompalintsSystem.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.ApplicationUser", b =>
                {
                    b.Navigation("Compalints_Solutions");

                    b.Navigation("ComplaintsRejecteds");

                    b.Navigation("UploadsComplaintes");

                    b.Navigation("UserRoles");

                    b.Navigation("UsersCommunications");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.Colleges", b =>
                {
                    b.Navigation("Departmentss");

                    b.Navigation("UploadsComplaintes");

                    b.Navigation("Users");

                    b.Navigation("UsersCommunications");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.ComplatinClassfaction", b =>
                {
                    b.Navigation("UploadsComplainte");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.Departments", b =>
                {
                    b.Navigation("SubDepartmentss");

                    b.Navigation("UploadsComplaintes");

                    b.Navigation("Users");

                    b.Navigation("UsersCommunications");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.Society", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.StagesComplaint", b =>
                {
                    b.Navigation("UploadsComplainte");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.StatusCompalint", b =>
                {
                    b.Navigation("UploadsComplainte");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.SubDepartments", b =>
                {
                    b.Navigation("UploadsComplaintes");

                    b.Navigation("Users");

                    b.Navigation("UsersCommunications");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.TypeCommunication", b =>
                {
                    b.Navigation("UsersCommunications");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.TypeComplaint", b =>
                {
                    b.Navigation("UploadsComplaintes");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.UploadsComplainte", b =>
                {
                    b.Navigation("Compalints_Solutions");

                    b.Navigation("ComplaintsRejecteds");

                    b.Navigation("ComplaintsUp");
                });
#pragma warning restore 612, 618
        }
    }
}
